# Liste cible des 300 races d'animaux domestiques pour Captivia v2.
# Les races utilisent la plage d'IDs réservée 2 000 000 001+ (jamais attribuée par GBIF,
# dont les clés vont jusqu'à ~3.1e8). La plage est documentée dans schema.prisma.
# Format : { class, fr, sci, breed_of } — breed_of = espèce de rattachement (ex: Chien)
# Les données éditoriales complètes (7 onglets) sont produites par les sous-agents
# via le contrat races-contract.md et importées par scripts/import-races.ts.

TARGET_RACES = [
    # ─── CHIENS (90) — Canis lupus familiaris ───
    {'class': 'mammifère', 'fr': 'Berger allemand', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Labrador Retriever', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Golden Retriever', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Bulldog français', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Bouledogue anglais', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Beagle', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Caniche', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Rottweiler', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Yorkshire Terrier', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Boxer', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Husky sibérien', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Dobermann', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Chihuahua', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Carlin', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Shih Tzu', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Border Collie', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Cocker Spaniel anglais', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Dalmatien', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Dogue allemand', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Épagneul breton', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Jack Russell Terrier', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Whippet', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Lévrier afghan', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Bichon maltais', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Berger australien', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Berger belge malinois', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Bouvier bernois', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Bull Terrier', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Cairn Terrier', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Cavalier King Charles', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Chow-chow', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Colley', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Corgi gallois', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Coton de Tuléar', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Dogue de Bordeaux', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Fox Terrier', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Lévrier whippet italien', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Mastiff', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Papillon', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Pékinois', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Pinscher nain', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Pitbull (American Staffordshire)', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Pomsky', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Poodle toy', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Shiba Inu', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Schnauzer nain', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Schnauzer géant', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Setter irlandais', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Setter anglais', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Shar Pei', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Spitz nain', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Staffordshire Bull Terrier', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Teckel', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Terrier écossais', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Terrier tibétain', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'West Highland White Terrier', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Akita Inu', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Alaskan Malamute', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'American Pit Bull Terrier', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Basset Hound', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Berger blanc suisse', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Berger des Pyrénées', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Bichon frisé', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Bloodhound', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Braque allemand', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Braque de Weimar', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Bullmastiff', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Caniche royal', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Chien de berger des Shetland', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Chien d’eau portugais', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Chien de montagne des Pyrénées', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Dogue argentin', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Épagneul cocker américain', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Épagneul king Charles', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Flat-Coated Retriever', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Galgo espagnol', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Greyhound', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Keeshond', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Kuvasz', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Lagotto Romagnolo', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Leonberg', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Lhassa Apso', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Malamute', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Mudi', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Néerlandais', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Norfolk Terrier', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Norvégien', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Otterhound', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Parson Russell Terrier', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Petit brabançon', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Petit chien lion', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Phalène', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Pudelpointer', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Rhodesian Ridgeback', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Saluki', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Samoyède', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Schapendoes', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Schipperke', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Silky Terrier', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Skye Terrier', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Sloughi', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Springer Spaniel anglais', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Sussex Spaniel', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Terre-Neuve', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Tosa', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Vizsla', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Weimaraner', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    {'class': 'mammifère', 'fr': 'Whippet italien', 'sci': 'Canis lupus familiaris', 'breed_of': 'Chien'},
    # ─── CHATS (45) — Felis catus ───
    {'class': 'mammifère', 'fr': 'Européen', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Persan', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Maine Coon', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Siamois', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Bengal', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'British Shorthair', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Scottish Fold', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Sphynx', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Abyssin', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Sacré de Birmanie', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Chartreux', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Devon Rex', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Exotic Shorthair', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Himalayen', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Korat', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Manx', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Norvégien (Skogkatt)', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Ocicat', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Oriental', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Ragdoll', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Russian Blue', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Savannah', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Sibérien', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Somali', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Tonkinois', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Turc de Van', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Angora turc', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Bombay', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Burmese', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Ceylan', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Chausie', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Cornish Rex', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Égyptien mau', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Khao Manee', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'LaPerm', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Munchkin', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Nebelung', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Peterbald', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Selkirk Rex', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Singapura', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Snowshoe', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Toyger', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Turc', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'Ussuri', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    {'class': 'mammifère', 'fr': 'York Chocolat', 'sci': 'Felis catus', 'breed_of': 'Chat'},
    # ─── LAPINS (20) — Oryctolagus cuniculus ───
    {'class': 'mammifère', 'fr': 'Lapin nain bélier', 'sci': 'Oryctolagus cuniculus', 'breed_of': 'Lapin domestique'},
    {'class': 'mammifère', 'fr': 'Lapin bélier français', 'sci': 'Oryctolagus cuniculus', 'breed_of': 'Lapin domestique'},
    {'class': 'mammifère', 'fr': 'Lapin nain', 'sci': 'Oryctolagus cuniculus', 'breed_of': 'Lapin domestique'},
    {'class': 'mammifère', 'fr': 'Lapin angora', 'sci': 'Oryctolagus cuniculus', 'breed_of': 'Lapin domestique'},
    {'class': 'mammifère', 'fr': 'Lapin rex', 'sci': 'Oryctolagus cuniculus', 'breed_of': 'Lapin domestique'},
    {'class': 'mammifère', 'fr': 'Lapin géant des Flandres', 'sci': 'Oryctolagus cuniculus', 'breed_of': 'Lapin domestique'},
    {'class': 'mammifère', 'fr': 'Lapin hollandais', 'sci': 'Oryctolagus cuniculus', 'breed_of': 'Lapin domestique'},
    {'class': 'mammifère', 'fr': 'Lapin lop', 'sci': 'Oryctolagus cuniculus', 'breed_of': 'Lapin domestique'},
    {'class': 'mammifère', 'fr': 'Lapin papillon', 'sci': 'Oryctolagus cuniculus', 'breed_of': 'Lapin domestique'},
    {'class': 'mammifère', 'fr': 'Lapin tête de lion', 'sci': 'Oryctolagus cuniculus', 'breed_of': 'Lapin domestique'},
    {'class': 'mammifère', 'fr': 'Lapin hermine', 'sci': 'Oryctolagus cuniculus', 'breed_of': 'Lapin domestique'},
    {'class': 'mammifère', 'fr': 'Lapin polonais', 'sci': 'Oryctolagus cuniculus', 'breed_of': 'Lapin domestique'},
    {'class': 'mammifère', 'fr': 'Lapin russe', 'sci': 'Oryctolagus cuniculus', 'breed_of': 'Lapin domestique'},
    {'class': 'mammifère', 'fr': 'Lapin satin', 'sci': 'Oryctolagus cuniculus', 'breed_of': 'Lapin domestique'},
    {'class': 'mammifère', 'fr': 'Lapin tacheté anglais', 'sci': 'Oryctolagus cuniculus', 'breed_of': 'Lapin domestique'},
    {'class': 'mammifère', 'fr': 'Lapin zibeline', 'sci': 'Oryctolagus cuniculus', 'breed_of': 'Lapin domestique'},
    {'class': 'mammifère', 'fr': 'Lapin argenté de Champagne', 'sci': 'Oryctolagus cuniculus', 'breed_of': 'Lapin domestique'},
    {'class': 'mammifère', 'fr': 'Lapin fauve de Bourgogne', 'sci': 'Oryctolagus cuniculus', 'breed_of': 'Lapin domestique'},
    {'class': 'mammifère', 'fr': 'Lapin géant papillon', 'sci': 'Oryctolagus cuniculus', 'breed_of': 'Lapin domestique'},
    {'class': 'mammifère', 'fr': 'Lapin Chinchilla', 'sci': 'Oryctolagus cuniculus', 'breed_of': 'Lapin domestique'},
    # ─── RONGEURS & PETITS MAMMIFÈRES (30) ───
    {'class': 'mammifère', 'fr': 'Cochon d’Inde abyssinien', 'sci': 'Cavia porcellus', 'breed_of': 'Cochon d’Inde'},
    {'class': 'mammifère', 'fr': 'Cochon d’Inde péruvien', 'sci': 'Cavia porcellus', 'breed_of': 'Cochon d’Inde'},
    {'class': 'mammifère', 'fr': 'Cochon d’Inde sheltie', 'sci': 'Cavia porcellus', 'breed_of': 'Cochon d’Inde'},
    {'class': 'mammifère', 'fr': 'Cochon d’Inde teddy', 'sci': 'Cavia porcellus', 'breed_of': 'Cochon d’Inde'},
    {'class': 'mammifère', 'fr': 'Cochon d’Inde texel', 'sci': 'Cavia porcellus', 'breed_of': 'Cochon d’Inde'},
    {'class': 'mammifère', 'fr': 'Cochon d’Inde skinny', 'sci': 'Cavia porcellus', 'breed_of': 'Cochon d’Inde'},
    {'class': 'mammifère', 'fr': 'Hamster doré', 'sci': 'Mesocricetus auratus', 'breed_of': 'Hamster'},
    {'class': 'mammifère', 'fr': 'Hamster russe', 'sci': 'Phodopus sungorus', 'breed_of': 'Hamster'},
    {'class': 'mammifère', 'fr': 'Hamster de Campbell', 'sci': 'Phodopus campbelli', 'breed_of': 'Hamster'},
    {'class': 'mammifère', 'fr': 'Hamster Roborovski', 'sci': 'Phodopus roborovskii', 'breed_of': 'Hamster'},
    {'class': 'mammifère', 'fr': 'Hamster chinois', 'sci': 'Cricetulus griseus', 'breed_of': 'Hamster'},
    {'class': 'mammifère', 'fr': 'Rat domestique', 'sci': 'Rattus norvegicus', 'breed_of': 'Rat'},
    {'class': 'mammifère', 'fr': 'Souris domestique', 'sci': 'Mus musculus', 'breed_of': 'Souris'},
    {'class': 'mammifère', 'fr': 'Gerbille de Mongolie', 'sci': 'Meriones unguiculatus', 'breed_of': 'Gerbille'},
    {'class': 'mammifère', 'fr': 'Chinchilla', 'sci': 'Chinchilla lanigera', 'breed_of': 'Chinchilla'},
    {'class': 'mammifère', 'fr': 'Octodon', 'sci': 'Octodon degus', 'breed_of': 'Octodon'},
    {'class': 'mammifère', 'fr': 'Écureuil de Corée', 'sci': 'Tamias sibiricus', 'breed_of': 'Écureuil'},
    {'class': 'mammifère', 'fr': 'Hérisson africain', 'sci': 'Atelerix albiventris', 'breed_of': 'Hérisson'},
    {'class': 'mammifère', 'fr': 'Furet', 'sci': 'Mustela putorius furo', 'breed_of': 'Furet'},
    {'class': 'mammifère', 'fr': 'Phalanger volant', 'sci': 'Petaurus breviceps', 'breed_of': 'Phalanger'},
    {'class': 'mammifère', 'fr': 'Cochon nain', 'sci': 'Sus scrofa domesticus', 'breed_of': 'Cochon'},
    {'class': 'mammifère', 'fr': 'Chèvre naine', 'sci': 'Capra aegagrus hircus', 'breed_of': 'Chèvre'},
    {'class': 'mammifère', 'fr': 'Alpaga', 'sci': 'Vicugna pacos', 'breed_of': 'Alpaga'},
    {'class': 'mammifère', 'fr': 'Lama', 'sci': 'Lama glama', 'breed_of': 'Lama'},
    {'class': 'mammifère', 'fr': 'Âne nain', 'sci': 'Equus asinus', 'breed_of': 'Âne'},
    {'class': 'mammifère', 'fr': 'Poney Shetland', 'sci': 'Equus ferus caballus', 'breed_of': 'Cheval'},
    {'class': 'mammifère', 'fr': 'Cheval miniature', 'sci': 'Equus ferus caballus', 'breed_of': 'Cheval'},
    {'class': 'mammifère', 'fr': 'Mouton nain', 'sci': 'Ovis aries', 'breed_of': 'Mouton'},
    {'class': 'mammifère', 'fr': 'Vache miniature', 'sci': 'Bos taurus', 'breed_of': 'Vache'},
    {'class': 'mammifère', 'fr': 'Gerboise', 'sci': 'Jaculus jaculus', 'breed_of': 'Gerboise'},
    # ─── OISEAUX (45) ───
    {'class': 'oiseau', 'fr': 'Perruche ondulée', 'sci': 'Melopsittacus undulatus', 'breed_of': 'Perruche'},
    {'class': 'oiseau', 'fr': 'Calopsitte élégante', 'sci': 'Nymphicus hollandicus', 'breed_of': 'Calopsitte'},
    {'class': 'oiseau', 'fr': 'Perroquet gris du Gabon', 'sci': 'Psittacus erithacus', 'breed_of': 'Perroquet'},
    {'class': 'oiseau', 'fr': 'Amazone à front bleu', 'sci': 'Amazona aestiva', 'breed_of': 'Amazone'},
    {'class': 'oiseau', 'fr': 'Ara ararauna', 'sci': 'Ara ararauna', 'breed_of': 'Ara'},
    {'class': 'oiseau', 'fr': 'Ara macao', 'sci': 'Ara macao', 'breed_of': 'Ara'},
    {'class': 'oiseau', 'fr': 'Ara hyacinthe', 'sci': 'Anodorhynchus hyacinthinus', 'breed_of': 'Ara'},
    {'class': 'oiseau', 'fr': 'Conure à joues vertes', 'sci': 'Pyrrhura molinae', 'breed_of': 'Conure'},
    {'class': 'oiseau', 'fr': 'Conure soleil', 'sci': 'Aratinga solstitialis', 'breed_of': 'Conure'},
    {'class': 'oiseau', 'fr': 'Inséparable rosegorge', 'sci': 'Agapornis roseicollis', 'breed_of': 'Inséparable'},
    {'class': 'oiseau', 'fr': 'Inséparable Fischer', 'sci': 'Agapornis fischeri', 'breed_of': 'Inséparable'},
    {'class': 'oiseau', 'fr': 'Perroquet youyou', 'sci': 'Poicephalus senegalus', 'breed_of': 'Perroquet'},
    {'class': 'oiseau', 'fr': 'Éclectus', 'sci': 'Eclectus roratus', 'breed_of': 'Perroquet'},
    {'class': 'oiseau', 'fr': 'Loriquet arc-en-ciel', 'sci': 'Trichoglossus moluccanus', 'breed_of': 'Loriquet'},
    {'class': 'oiseau', 'fr': 'Cacatoès rosalbin', 'sci': 'Eolophus roseicapilla', 'breed_of': 'Cacatoès'},
    {'class': 'oiseau', 'fr': 'Canari', 'sci': 'Serinus canaria', 'breed_of': 'Canari'},
    {'class': 'oiseau', 'fr': 'Diamant mandarin', 'sci': 'Taeniopygia guttata', 'breed_of': 'Diamant'},
    {'class': 'oiseau', 'fr': 'Moineau du Japon', 'sci': 'Lonchura striata domestica', 'breed_of': 'Moineau'},
    {'class': 'oiseau', 'fr': 'Bengali', 'sci': 'Lonchura striata', 'breed_of': 'Bengali'},
    {'class': 'oiseau', 'fr': 'Padda de Java', 'sci': 'Padda oryzivora', 'breed_of': 'Padda'},
    {'class': 'oiseau', 'fr': 'Chardonneret', 'sci': 'Carduelis carduelis', 'breed_of': 'Chardonneret'},
    {'class': 'oiseau', 'fr': 'Bouvreuil', 'sci': 'Pyrrhula pyrrhula', 'breed_of': 'Bouvreuil'},
    {'class': 'oiseau', 'fr': 'Perruche à collier', 'sci': 'Psittacula krameri', 'breed_of': 'Perruche'},
    {'class': 'oiseau', 'fr': 'Perruche Alexandre', 'sci': 'Psittacula eupatria', 'breed_of': 'Perruche'},
    {'class': 'oiseau', 'fr': 'Perruche de Bourke', 'sci': 'Neopsephotus bourkii', 'breed_of': 'Perruche'},
    {'class': 'oiseau', 'fr': 'Perruche turquoisine', 'sci': 'Neophema pulchella', 'breed_of': 'Perruche'},
    {'class': 'oiseau', 'fr': 'Perruche omnicolore', 'sci': 'Platycercus eximius', 'breed_of': 'Perruche'},
    {'class': 'oiseau', 'fr': 'Ara noble', 'sci': 'Diopsittaca nobilis', 'breed_of': 'Ara'},
    {'class': 'oiseau', 'fr': 'Aratinga jandaya', 'sci': 'Aratinga jandaya', 'breed_of': 'Conure'},
    {'class': 'oiseau', 'fr': 'Caïque à tête noire', 'sci': 'Pionites melanocephalus', 'breed_of': 'Caïque'},
    {'class': 'oiseau', 'fr': 'Pionus à tête bleue', 'sci': 'Pionus menstruus', 'breed_of': 'Pionus'},
    {'class': 'oiseau', 'fr': 'Toui été', 'sci': 'Forpus passerinus', 'breed_of': 'Toui'},
    {'class': 'oiseau', 'fr': 'Toui à lunettes', 'sci': 'Forpus conspicillatus', 'breed_of': 'Toui'},
    {'class': 'oiseau', 'fr': 'Astrild ondulé', 'sci': 'Estrilda astrild', 'breed_of': 'Astrild'},
    {'class': 'oiseau', 'fr': 'Capucin damier', 'sci': 'Lonchura punctulata', 'breed_of': 'Capucin'},
    {'class': 'oiseau', 'fr': 'Colombe diamant', 'sci': 'Geopelia cuneata', 'breed_of': 'Colombe'},
    {'class': 'oiseau', 'fr': 'Tourterelle à collier', 'sci': 'Streptopelia risoria', 'breed_of': 'Tourterelle'},
    {'class': 'oiseau', 'fr': 'Poule soie', 'sci': 'Gallus gallus domesticus', 'breed_of': 'Poule'},
    {'class': 'oiseau', 'fr': 'Poule Brahma', 'sci': 'Gallus gallus domesticus', 'breed_of': 'Poule'},
    {'class': 'oiseau', 'fr': 'Poule Sussex', 'sci': 'Gallus gallus domesticus', 'breed_of': 'Poule'},
    {'class': 'oiseau', 'fr': 'Poule Wyandotte', 'sci': 'Gallus gallus domesticus', 'breed_of': 'Poule'},
    {'class': 'oiseau', 'fr': 'Poule Leghorn', 'sci': 'Gallus gallus domesticus', 'breed_of': 'Poule'},
    {'class': 'oiseau', 'fr': 'Poule Orpington', 'sci': 'Gallus gallus domesticus', 'breed_of': 'Poule'},
    {'class': 'oiseau', 'fr': 'Canard de Barbarie', 'sci': 'Cairina moschata', 'breed_of': 'Canard'},
    {'class': 'oiseau', 'fr': 'Oie de Toulouse', 'sci': 'Anser anser domesticus', 'breed_of': 'Oie'},
    # ─── REPTILES (40) ───
    {'class': 'reptile', 'fr': 'Gecko léopard', 'sci': 'Eublepharis macularius', 'breed_of': 'Gecko'},
    {'class': 'reptile', 'fr': 'Gecko à crête', 'sci': 'Correlophus ciliatus', 'breed_of': 'Gecko'},
    {'class': 'reptile', 'fr': 'Gecko diurne de Madagascar', 'sci': 'Phelsuma madagascariensis', 'breed_of': 'Gecko'},
    {'class': 'reptile', 'fr': 'Caméléon casqué', 'sci': 'Chamaeleo calyptratus', 'breed_of': 'Caméléon'},
    {'class': 'reptile', 'fr': 'Caméléon panthère', 'sci': 'Furcifer pardalis', 'breed_of': 'Caméléon'},
    {'class': 'reptile', 'fr': 'Iguane vert', 'sci': 'Iguana iguana', 'breed_of': 'Iguane'},
    {'class': 'reptile', 'fr': 'Anolis vert', 'sci': 'Anolis carolinensis', 'breed_of': 'Anolis'},
    {'class': 'reptile', 'fr': 'Agame barbu', 'sci': 'Pogona vitticeps', 'breed_of': 'Agame'},
    {'class': 'reptile', 'fr': 'Scinque à langue bleue', 'sci': 'Tiliqua scincoides', 'breed_of': 'Scinque'},
    {'class': 'reptile', 'fr': 'Tégou argentin', 'sci': 'Salvator merianae', 'breed_of': 'Tégou'},
    {'class': 'reptile', 'fr': 'Varan d’eau', 'sci': 'Varanus salvator', 'breed_of': 'Varan'},
    {'class': 'reptile', 'fr': 'Python royal', 'sci': 'Python regius', 'breed_of': 'Python'},
    {'class': 'reptile', 'fr': 'Python réticulé', 'sci': 'Malayopython reticulatus', 'breed_of': 'Python'},
    {'class': 'reptile', 'fr': 'Boa constricteur', 'sci': 'Boa constrictor', 'breed_of': 'Boa'},
    {'class': 'reptile', 'fr': 'Boa émeraude', 'sci': 'Corallus caninus', 'breed_of': 'Boa'},
    {'class': 'reptile', 'fr': 'Serpent des blés', 'sci': 'Pantherophis guttatus', 'breed_of': 'Serpent'},
    {'class': 'reptile', 'fr': 'Serpent roi', 'sci': 'Lampropeltis getula', 'breed_of': 'Serpent'},
    {'class': 'reptile', 'fr': 'Serpent ratier', 'sci': 'Elaphe obsoleta', 'breed_of': 'Serpent'},
    {'class': 'reptile', 'fr': 'Couleuvre à nez plat', 'sci': 'Heterodon nasicus', 'breed_of': 'Serpent'},
    {'class': 'reptile', 'fr': 'Python vert', 'sci': 'Morelia viridis', 'breed_of': 'Python'},
    {'class': 'reptile', 'fr': 'Boa arc-en-ciel', 'sci': 'Epicrates cenchria', 'breed_of': 'Boa'},
    {'class': 'reptile', 'fr': 'Tortue grecque', 'sci': 'Testudo graeca', 'breed_of': 'Tortue'},
    {'class': 'reptile', 'fr': 'Tortue Hermann', 'sci': 'Testudo hermanni', 'breed_of': 'Tortue'},
    {'class': 'reptile', 'fr': 'Tortue sulcata', 'sci': 'Centrochelys sulcata', 'breed_of': 'Tortue'},
    {'class': 'reptile', 'fr': 'Tortue léopard', 'sci': 'Stigmochelys pardalis', 'breed_of': 'Tortue'},
    {'class': 'reptile', 'fr': 'Tortue à oreilles rouges', 'sci': 'Trachemys scripta elegans', 'breed_of': 'Tortue'},
    {'class': 'reptile', 'fr': 'Tortue de Floride', 'sci': 'Trachemys scripta', 'breed_of': 'Tortue'},
    {'class': 'reptile', 'fr': 'Tortue peinte', 'sci': 'Chrysemys picta', 'breed_of': 'Tortue'},
    {'class': 'reptile', 'fr': 'Tortue musquée', 'sci': 'Sternotherus odoratus', 'breed_of': 'Tortue'},
    {'class': 'reptile', 'fr': 'Tortue boîte', 'sci': 'Terrapene carolina', 'breed_of': 'Tortue'},
    {'class': 'reptile', 'fr': 'Gecko tokay', 'sci': 'Gekko gecko', 'breed_of': 'Gecko'},
    {'class': 'reptile', 'fr': 'Lézard à collerette', 'sci': 'Chlamydosaurus kingii', 'breed_of': 'Lézard'},
    {'class': 'reptile', 'fr': 'Varan de Savane', 'sci': 'Varanus exanthematicus', 'breed_of': 'Varan'},
    {'class': 'reptile', 'fr': 'Python de Seba', 'sci': 'Python sebae', 'breed_of': 'Python'},
    {'class': 'reptile', 'fr': 'Crotale (serpent à sonnette)', 'sci': 'Crotalus atrox', 'breed_of': 'Serpent'},
    {'class': 'reptile', 'fr': 'Mamba noir', 'sci': 'Dendroaspis polylepis', 'breed_of': 'Serpent'},
    {'class': 'reptile', 'fr': 'Cobra royal', 'sci': 'Ophiophagus hannah', 'breed_of': 'Serpent'},
    {'class': 'reptile', 'fr': 'Vipère', 'sci': 'Vipera berus', 'breed_of': 'Serpent'},
    {'class': 'reptile', 'fr': 'Anaconda vert', 'sci': 'Eunectes murinus', 'breed_of': 'Boa'},
    {'class': 'reptile', 'fr': 'Caméléon de Jackson', 'sci': 'Trioceros jacksonii', 'breed_of': 'Caméléon'},
    # ─── AMPHIBIENS (15) ───
    {'class': 'amphibien', 'fr': 'Axolotl', 'sci': 'Ambystoma mexicanum', 'breed_of': 'Axolotl'},
    {'class': 'amphibien', 'fr': 'Grenouille à griffes', 'sci': 'Xenopus laevis', 'breed_of': 'Grenouille'},
    {'class': 'amphibien', 'fr': 'Rainette arboricole', 'sci': 'Hyla arborea', 'breed_of': 'Rainette'},
    {'class': 'amphibien', 'fr': 'Rainette verte', 'sci': 'Litoria caerulea', 'breed_of': 'Rainette'},
    {'class': 'amphibien', 'fr': 'Dendrobate', 'sci': 'Dendrobates tinctorius', 'breed_of': 'Dendrobate'},
    {'class': 'amphibien', 'fr': 'Dendrobate bleu', 'sci': 'Dendrobates azureus', 'breed_of': 'Dendrobate'},
    {'class': 'amphibien', 'fr': 'Triton', 'sci': 'Triturus vulgaris', 'breed_of': 'Triton'},
    {'class': 'amphibien', 'fr': 'Salamandre', 'sci': 'Salamandra salamandra', 'breed_of': 'Salamandre'},
    {'class': 'amphibien', 'fr': 'Grenouille taureau', 'sci': 'Lithobates catesbeianus', 'breed_of': 'Grenouille'},
    {'class': 'amphibien', 'fr': 'Crapaud', 'sci': 'Bufo bufo', 'breed_of': 'Crapaud'},
    {'class': 'amphibien', 'fr': 'Xénope', 'sci': 'Xenopus tropicalis', 'breed_of': 'Xénope'},
    {'class': 'amphibien', 'fr': 'Hylidé', 'sci': 'Hyla cinerea', 'breed_of': 'Rainette'},
    {'class': 'amphibien', 'fr': 'Pacman (Ceratophrys)', 'sci': 'Ceratophrys ornata', 'breed_of': 'Grenouille'},
    {'class': 'amphibien', 'fr': 'Grenouille tomato', 'sci': 'Dyscophus antongilii', 'breed_of': 'Grenouille'},
    {'class': 'amphibien', 'fr': 'Triton crêté', 'sci': 'Triturus cristatus', 'breed_of': 'Triton'},
    # ─── POISSONS (35) ───
    {'class': 'poisson', 'fr': 'Guppy', 'sci': 'Poecilia reticulata', 'breed_of': 'Guppy'},
    {'class': 'poisson', 'fr': 'Néon bleu', 'sci': 'Paracheirodon innesi', 'breed_of': 'Tétra'},
    {'class': 'poisson', 'fr': 'Néon noir', 'sci': 'Hyphessobrycon herbertaxelrodi', 'breed_of': 'Tétra'},
    {'class': 'poisson', 'fr': 'Molly', 'sci': 'Poecilia sphenops', 'breed_of': 'Molly'},
    {'class': 'poisson', 'fr': 'Platy', 'sci': 'Xiphophorus maculatus', 'breed_of': 'Platy'},
    {'class': 'poisson', 'fr': 'Xipho', 'sci': 'Xiphophorus hellerii', 'breed_of': 'Xipho'},
    {'class': 'poisson', 'fr': 'Combattant (Betta)', 'sci': 'Betta splendens', 'breed_of': 'Betta'},
    {'class': 'poisson', 'fr': 'Poisson rouge', 'sci': 'Carassius auratus', 'breed_of': 'Poisson rouge'},
    {'class': 'poisson', 'fr': 'Poisson rouge fantail', 'sci': 'Carassius auratus', 'breed_of': 'Poisson rouge'},
    {'class': 'poisson', 'fr': 'Poisson rouge oranda', 'sci': 'Carassius auratus', 'breed_of': 'Poisson rouge'},
    {'class': 'poisson', 'fr': 'Poisson rouge ryukin', 'sci': 'Carassius auratus', 'breed_of': 'Poisson rouge'},
    {'class': 'poisson', 'fr': 'Poisson rouge black moor', 'sci': 'Carassius auratus', 'breed_of': 'Poisson rouge'},
    {'class': 'poisson', 'fr': 'Corydoras', 'sci': 'Corydoras paleatus', 'breed_of': 'Corydoras'},
    {'class': 'poisson', 'fr': 'Otocinclus', 'sci': 'Otocinclus affinis', 'breed_of': 'Otocinclus'},
    {'class': 'poisson', 'fr': 'Ancistrus', 'sci': 'Ancistrus cirrhosus', 'breed_of': 'Ancistrus'},
    {'class': 'poisson', 'fr': 'Scalaire', 'sci': 'Pterophyllum scalare', 'breed_of': 'Scalaire'},
    {'class': 'poisson', 'fr': 'Discus', 'sci': 'Symphysodon aequifasciatus', 'breed_of': 'Discus'},
    {'class': 'poisson', 'fr': 'Ramirezi', 'sci': 'Mikrogeophagus ramirezi', 'breed_of': 'Ramirezi'},
    {'class': 'poisson', 'fr': 'Apistogramma', 'sci': 'Apistogramma agassizii', 'breed_of': 'Apistogramma'},
    {'class': 'poisson', 'fr': 'Tétra cardinal', 'sci': 'Paracheirodon axelrodi', 'breed_of': 'Tétra'},
    {'class': 'poisson', 'fr': 'Tétra citron', 'sci': 'Hyphessobrycon pulchripinnis', 'breed_of': 'Tétra'},
    {'class': 'poisson', 'fr': 'Tétra cuivré', 'sci': 'Hasemania nana', 'breed_of': 'Tétra'},
    {'class': 'poisson', 'fr': 'Barbus cerise', 'sci': 'Puntius titteya', 'breed_of': 'Barbus'},
    {'class': 'poisson', 'fr': 'Barbus de Sumatra', 'sci': 'Puntigrus tetrazona', 'breed_of': 'Barbus'},
    {'class': 'poisson', 'fr': 'Danio zébré', 'sci': 'Danio rerio', 'breed_of': 'Danio'},
    {'class': 'poisson', 'fr': 'Danio perlé', 'sci': 'Danio margaritatus', 'breed_of': 'Danio'},
    {'class': 'poisson', 'fr': 'Rasbora arlequin', 'sci': 'Trigonostigma heteromorpha', 'breed_of': 'Rasbora'},
    {'class': 'poisson', 'fr': 'Gourami bleu', 'sci': 'Trichopodus trichopterus', 'breed_of': 'Gourami'},
    {'class': 'poisson', 'fr': 'Gourami nain', 'sci': 'Trichogaster lalius', 'breed_of': 'Gourami'},
    {'class': 'poisson', 'fr': 'Gourami perlé', 'sci': 'Trichopodus leerii', 'breed_of': 'Gourami'},
    {'class': 'poisson', 'fr': 'Guppy endler', 'sci': 'Poecilia wingei', 'breed_of': 'Guppy'},
    {'class': 'poisson', 'fr': 'Platy variatus', 'sci': 'Xiphophorus variatus', 'breed_of': 'Platy'},
    {'class': 'poisson', 'fr': 'Molly voile', 'sci': 'Poecilia latipinna', 'breed_of': 'Molly'},
    {'class': 'poisson', 'fr': 'Cichlidé perroquet', 'sci': 'Amphilophus citrinellus × vieja', 'breed_of': 'Cichlidé'},
    {'class': 'poisson', 'fr': 'Kribensis', 'sci': 'Pelvicachromis pulcher', 'breed_of': 'Cichlidé'},
    # ─── INVERTÉBRÉS (10) ───
    {'class': 'arachnide', 'fr': 'Mygale rose', 'sci': 'Grammostola rosea', 'breed_of': 'Mygale'},
    {'class': 'arachnide', 'fr': 'Mygale mexicaine', 'sci': 'Brachypelma smithi', 'breed_of': 'Mygale'},
    {'class': 'arachnide', 'fr': 'Mygale tigre', 'sci': 'Psalmopoeus irminia', 'breed_of': 'Mygale'},
    {'class': 'arachnide', 'fr': 'Scorpion empereur', 'sci': 'Pandinus imperator', 'breed_of': 'Scorpion'},
    {'class': 'arachnide', 'fr': 'Scorpion à queue jaune', 'sci': 'Androctonus australis', 'breed_of': 'Scorpion'},
    {'class': 'insecte', 'fr': 'Phasme bâton', 'sci': 'Carausius morosus', 'breed_of': 'Phasme'},
    {'class': 'insecte', 'fr': 'Mante religieuse', 'sci': 'Mantis religiosa', 'breed_of': 'Mante'},
    {'class': 'insecte', 'fr': 'Blatte de Madagascar', 'sci': 'Gromphadorhina portentosa', 'breed_of': 'Blatte'},
    {'class': 'insecte', 'fr': 'Escargot géant africain', 'sci': 'Achatina fulica', 'breed_of': 'Escargot'},
    {'class': 'insecte', 'fr': 'Crevette Red Cherry', 'sci': 'Neocaridina davidi', 'breed_of': 'Crevette'},
]
