# Liste cible des 300 espèces domesticables pour Captivia v1.
# Format : { classe, nom commun FR, nom scientifique (pour résolution GBIF) }
# Les données éditoriales seront générées par le pipeline sourcé (GBIF + Wikipedia + Wikidata).
# Clés utilisées par SpeciesProfile.category : mammal, bird, reptile, amphibian, fish, invertebrate
TARGET_SPECIES = [    {'class': 'mammal', 'fr': 'Chien', 'sci': 'Canis lupus familiaris'},
    {'class': 'mammal', 'fr': 'Chat', 'sci': 'Felis catus'},
    {'class': 'mammal', 'fr': 'Furet', 'sci': 'Mustela putorius furo'},
    {'class': 'mammal', 'fr': 'Lapin domestique', 'sci': 'Oryctolagus cuniculus'},
    {'class': 'mammal', 'fr': "Cochon d'Inde", 'sci': 'Cavia porcellus'},
    {'class': 'mammal', 'fr': 'Hamster doré', 'sci': 'Mesocricetus auratus'},
    {'class': 'mammal', 'fr': 'Hamster russe', 'sci': 'Phodopus sungorus'},
    {'class': 'mammal', 'fr': 'Hamster de Campbell', 'sci': 'Phodopus campbelli'},
    {'class': 'mammal', 'fr': 'Hamster Roborovski', 'sci': 'Phodopus roborovskii'},
    {'class': 'mammal', 'fr': 'Rat domestique', 'sci': 'Rattus norvegicus'},
    {'class': 'mammal', 'fr': 'Souris domestique', 'sci': 'Mus musculus'},
    {'class': 'mammal', 'fr': 'Gerbille de Mongolie', 'sci': 'Meriones unguiculatus'},
    {'class': 'mammal', 'fr': 'Chinchilla', 'sci': 'Chinchilla lanigera'},
    {'class': 'mammal', 'fr': 'Octodon', 'sci': 'Octodon degus'},
    {'class': 'mammal', 'fr': 'Écureuil de Corée', 'sci': 'Tamias sibiricus'},
    {'class': 'mammal', 'fr': 'Hérisson africain', 'sci': 'Atelerix albiventris'},
    {'class': 'mammal', 'fr': 'Opossum pygmée', 'sci': 'Monodelphis domestica'},
    {'class': 'mammal', 'fr': 'Phalanger volant', 'sci': 'Petaurus breviceps'},
    {'class': 'mammal', 'fr': 'Souris des moissons', 'sci': 'Micromys minutus'},
    {'class': 'mammal', 'fr': 'Cochon nain', 'sci': 'Sus scrofa domesticus'},
    {'class': 'mammal', 'fr': 'Chèvre naine', 'sci': 'Capra aegagrus hircus'},
    {'class': 'mammal', 'fr': 'Mouton', 'sci': 'Ovis aries'},
    {'class': 'mammal', 'fr': 'Vache miniature', 'sci': 'Bos taurus'},
    {'class': 'mammal', 'fr': 'Cheval miniature', 'sci': 'Equus ferus caballus'},
    {'class': 'mammal', 'fr': 'Âne', 'sci': 'Equus asinus'},
    {'class': 'mammal', 'fr': 'Alpaga', 'sci': 'Vicugna pacos'},
    {'class': 'mammal', 'fr': 'Lama', 'sci': 'Lama glama'},
    {'class': 'mammal', 'fr': 'Wallaby de Bennett', 'sci': 'Notamacropus rufogriseus'},
    {'class': 'mammal', 'fr': 'Kinkajou', 'sci': 'Potos flavus'},
    {'class': 'mammal', 'fr': 'Genette', 'sci': 'Genetta genetta'},
    {'class': 'mammal', 'fr': 'Serval', 'sci': 'Leptailurus serval'},
    {'class': 'mammal', 'fr': 'Chat de Geoffroy', 'sci': 'Leopardus geoffroyi'},
    {'class': 'mammal', 'fr': 'Écureuil gris', 'sci': 'Sciurus carolinensis'},
    {'class': 'mammal', 'fr': 'Écureuil roux', 'sci': 'Sciurus vulgaris'},
    {'class': 'mammal', 'fr': 'Mangouste', 'sci': 'Herpestes ichneumon'},
    {'class': 'mammal', 'fr': 'Coati', 'sci': 'Nasua nasua'},
    {'class': 'mammal', 'fr': 'Raton laveur', 'sci': 'Procyon lotor'},
    {'class': 'mammal', 'fr': 'Putois', 'sci': 'Mustela putorius'},
    {'class': 'mammal', 'fr': 'Vison', 'sci': 'Neovison vison'},
    {'class': 'mammal', 'fr': 'Loutre', 'sci': 'Lutra lutra'},
    {'class': 'mammal', 'fr': 'Suricate', 'sci': 'Suricata suricatta'},
    {'class': 'mammal', 'fr': 'Lemur catta', 'sci': 'Lemur catta'},
    {'class': 'mammal', 'fr': 'Tamarin', 'sci': 'Saguinus oedipus'},
    {'class': 'mammal', 'fr': 'Ouistiti', 'sci': 'Callithrix jacchus'},
    {'class': 'mammal', 'fr': 'Capybara', 'sci': 'Hydrochoerus hydrochaeris'},
    {'class': 'mammal', 'fr': 'Porc-épic', 'sci': 'Hystrix cristata'},
    {'class': 'mammal', 'fr': 'Agouti', 'sci': 'Dasyprocta leporina'},
    {'class': 'mammal', 'fr': 'Paca', 'sci': 'Cuniculus paca'},
    {'class': 'mammal', 'fr': 'Viscache', 'sci': 'Lagidium viscacia'},
    {'class': 'mammal', 'fr': 'Mara', 'sci': 'Dolichotis patagonum'},
    {'class': 'mammal', 'fr': 'Écureuil volant', 'sci': 'Pteromys volans'},
    {'class': 'mammal', 'fr': 'Galago', 'sci': 'Galago senegalensis'},
    {'class': 'mammal', 'fr': 'Tarsier', 'sci': 'Tarsius syrichta'},
    {'class': 'mammal', 'fr': 'Binturong', 'sci': 'Arctictis binturong'},
    {'class': 'mammal', 'fr': 'Fossa', 'sci': 'Cryptoprocta ferox'},
    {'class': 'mammal', 'fr': 'Caracal', 'sci': 'Caracal caracal'},
    {'class': 'mammal', 'fr': 'Ocelot', 'sci': 'Leopardus pardalis'},
    {'class': 'mammal', 'fr': 'Chat pêcheur', 'sci': 'Prionailurus viverrinus'},
    {'class': 'mammal', 'fr': 'Chaus', 'sci': 'Felis chaus'},
    {'class': 'mammal', 'fr': 'Bœuf musqué', 'sci': 'Ovibos moschatus'},
    {'class': 'mammal', 'fr': 'Cerf sika', 'sci': 'Cervus nippon'},
    {'class': 'mammal', 'fr': 'Daim', 'sci': 'Dama dama'},
    {'class': 'mammal', 'fr': 'Antilope cervicapre', 'sci': 'Antilope cervicapra'},
    {'class': 'bird', 'fr': 'Perruche ondulée', 'sci': 'Melopsittacus undulatus'},
    {'class': 'bird', 'fr': 'Perruche à collier', 'sci': 'Psittacula krameri'},
    {'class': 'bird', 'fr': 'Perruche calopsitte', 'sci': 'Nymphicus hollandicus'},
    {'class': 'bird', 'fr': 'Perruche de Bourke', 'sci': 'Neopsephotus bourkii'},
    {'class': 'bird', 'fr': 'Perruche turquoisine', 'sci': 'Neophema pulchella'},
    {'class': 'bird', 'fr': 'Perruche élégante', 'sci': 'Neophema elegans'},
    {'class': 'bird', 'fr': 'Inséparable rosegorge', 'sci': 'Agapornis roseicollis'},
    {'class': 'bird', 'fr': 'Inséparable de Fischer', 'sci': 'Agapornis fischeri'},
    {'class': 'bird', 'fr': 'Inséparable masqué', 'sci': 'Agapornis personatus'},
    {'class': 'bird', 'fr': 'Gris du Gabon', 'sci': 'Psittacus erithacus'},
    {'class': 'bird', 'fr': 'Amazone à front bleu', 'sci': 'Amazona aestiva'},
    {'class': 'bird', 'fr': 'Amazone à front blanc', 'sci': 'Amazona albifrons'},
    {'class': 'bird', 'fr': 'Ara ararauna', 'sci': 'Ara ararauna'},
    {'class': 'bird', 'fr': 'Ara macao', 'sci': 'Ara macao'},
    {'class': 'bird', 'fr': 'Ara militaire', 'sci': 'Ara militaris'},
    {'class': 'bird', 'fr': 'Ara noble', 'sci': 'Diopsittaca nobilis'},
    {'class': 'bird', 'fr': 'Conure à joues vertes', 'sci': 'Pyrrhura molinae'},
    {'class': 'bird', 'fr': 'Conure soleil', 'sci': 'Aratinga solstitialis'},
    {'class': 'bird', 'fr': 'Conure veuve', 'sci': 'Myiopsitta monachus'},
    {'class': 'bird', 'fr': 'Cacatoès rosalbin', 'sci': 'Eolophus roseicapilla'},
    {'class': 'bird', 'fr': 'Cacatoès à huppe jaune', 'sci': 'Cacatua galerita'},
    {'class': 'bird', 'fr': 'Cacatoès blanc', 'sci': 'Cacatua alba'},
    {'class': 'bird', 'fr': 'Perroquet youyou', 'sci': 'Poicephalus senegalus'},
    {'class': 'bird', 'fr': 'Perroquet de Meyer', 'sci': 'Poicephalus meyeri'},
    {'class': 'bird', 'fr': 'Éclectus', 'sci': 'Eclectus roratus'},
    {'class': 'bird', 'fr': 'Perroquet à tête de prune', 'sci': 'Psittacula cyanocephala'},
    {'class': 'bird', 'fr': 'Lori de Swainson', 'sci': 'Trichoglossus moluccanus'},
    {'class': 'bird', 'fr': 'Canari', 'sci': 'Serinus canaria'},
    {'class': 'bird', 'fr': 'Diamant mandarin', 'sci': 'Taeniopygia guttata'},
    {'class': 'bird', 'fr': 'Moineau du Japon', 'sci': 'Lonchura striata domestica'},
    {'class': 'bird', 'fr': 'Padda de Java', 'sci': 'Lonchura oryzivora'},
    {'class': 'bird', 'fr': 'Capucin damier', 'sci': 'Lonchura punctulata'},
    {'class': 'bird', 'fr': 'Astrild à pointe', 'sci': 'Estrilda caerulescens'},
    {'class': 'bird', 'fr': 'Gouldien', 'sci': 'Chloebia gouldiae'},
    {'class': 'bird', 'fr': 'Cardinal rouge', 'sci': 'Cardinalis cardinalis'},
    {'class': 'bird', 'fr': 'Rossignol du Japon', 'sci': 'Leiothrix lutea'},
    {'class': 'bird', 'fr': 'Bruant du Japon', 'sci': 'Emberiza cioides'},
    {'class': 'bird', 'fr': 'Colombe diamant', 'sci': 'Geopelia cuneata'},
    {'class': 'bird', 'fr': 'Tourterelle domestique', 'sci': 'Streptopelia risoria'},
    {'class': 'bird', 'fr': 'Pigeon domestique', 'sci': 'Columba livia domestica'},
    {'class': 'bird', 'fr': 'Poule naine', 'sci': 'Gallus gallus domesticus'},
    {'class': 'bird', 'fr': 'Coq de combat', 'sci': 'Gallus gallus'},
    {'class': 'bird', 'fr': 'Canard colvert', 'sci': 'Anas platyrhynchos'},
    {'class': 'bird', 'fr': 'Canard mandarin', 'sci': 'Aix galericulata'},
    {'class': 'bird', 'fr': 'Canard carolin', 'sci': 'Aix sponsa'},
    {'class': 'bird', 'fr': 'Oie domestique', 'sci': 'Anser anser domesticus'},
    {'class': 'bird', 'fr': 'Dinde domestique', 'sci': 'Meleagris gallopavo'},
    {'class': 'bird', 'fr': 'Caille du Japon', 'sci': 'Coturnix japonica'},
    {'class': 'bird', 'fr': 'Faisan doré', 'sci': 'Chrysolophus pictus'},
    {'class': 'bird', 'fr': 'Faisan de Lady Amherst', 'sci': 'Chrysolophus amherstiae'},
    {'class': 'bird', 'fr': 'Paon bleu', 'sci': 'Pavo cristatus'},
    {'class': 'bird', 'fr': 'Cygne tuberculé', 'sci': 'Cygnus olor'},
    {'class': 'bird', 'fr': 'Émeu', 'sci': 'Dromaius novaehollandiae'},
    {'class': 'bird', 'fr': 'Autruche', 'sci': 'Struthio camelus'},
    {'class': 'bird', 'fr': 'Toucan toco', 'sci': 'Ramphastos toco'},
    {'class': 'bird', 'fr': 'Calao', 'sci': 'Buceros rhinoceros'},
    {'class': 'bird', 'fr': 'Corbeau familier', 'sci': 'Corvus corax'},
    {'class': 'bird', 'fr': "Grand-duc d'Europe", 'sci': 'Bubo bubo'},
    {'class': 'reptile', 'fr': 'Gecko léopard', 'sci': 'Eublepharis macularius'},
    {'class': 'reptile', 'fr': 'Gecko à crête', 'sci': 'Correlophus ciliatus'},
    {'class': 'reptile', 'fr': 'Gecko géant de Madagascar', 'sci': 'Phelsuma grandis'},
    {'class': 'reptile', 'fr': 'Gecko diurne de Madagascar', 'sci': 'Phelsuma madagascariensis'},
    {'class': 'reptile', 'fr': "Gecko de l'ouest", 'sci': 'Rhacodactylus leachianus'},
    {'class': 'reptile', 'fr': 'Gecko satanique', 'sci': 'Uroplatus phantasticus'},
    {'class': 'reptile', 'fr': 'Scinque à langue bleue', 'sci': 'Tiliqua scincoides'},
    {'class': 'reptile', 'fr': 'Scinque de Schneider', 'sci': 'Eumeces schneideri'},
    {'class': 'reptile', 'fr': 'Agame barbu', 'sci': 'Pogona vitticeps'},
    {'class': 'reptile', 'fr': 'Agame à tête rouge', 'sci': 'Agama agama'},
    {'class': 'reptile', 'fr': 'Iguane vert', 'sci': 'Iguana iguana'},
    {'class': 'reptile', 'fr': 'Iguane des Petites Antilles', 'sci': 'Iguana delicatissima'},
    {'class': 'reptile', 'fr': 'Anole vert', 'sci': 'Anolis carolinensis'},
    {'class': 'reptile', 'fr': 'Anole de Cuba', 'sci': 'Anolis equestris'},
    {'class': 'reptile', 'fr': 'Basilic vert', 'sci': 'Basiliscus plumifrons'},
    {'class': 'reptile', 'fr': 'Caméléon casqué', 'sci': 'Chamaeleo calyptratus'},
    {'class': 'reptile', 'fr': 'Caméléon panthère', 'sci': 'Furcifer pardalis'},
    {'class': 'reptile', 'fr': 'Caméléon de Jackson', 'sci': 'Trioceros jacksonii'},
    {'class': 'reptile', 'fr': 'Caméléon de Parson', 'sci': 'Calumma parsonii'},
    {'class': 'reptile', 'fr': 'Varan du Nil', 'sci': 'Varanus niloticus'},
    {'class': 'reptile', 'fr': "Varan d'eau", 'sci': 'Varanus salvator'},
    {'class': 'reptile', 'fr': 'Varan de Komodo', 'sci': 'Varanus komodoensis'},
    {'class': 'reptile', 'fr': 'Varan des steppes', 'sci': 'Varanus exanthematicus'},
    {'class': 'reptile', 'fr': 'Varan de Gillen', 'sci': 'Varanus gilleni'},
    {'class': 'reptile', 'fr': 'Téju rouge', 'sci': 'Salvator rufescens'},
    {'class': 'reptile', 'fr': 'Téju noir et blanc', 'sci': 'Salvator merianae'},
    {'class': 'reptile', 'fr': 'Lézard à collerette', 'sci': 'Chlamydosaurus kingii'},
    {'class': 'reptile', 'fr': 'Lézard ocellé', 'sci': 'Timon lepidus'},
    {'class': 'reptile', 'fr': 'Orvet fragile', 'sci': 'Anguis fragilis'},
    {'class': 'reptile', 'fr': 'Python royal', 'sci': 'Python regius'},
    {'class': 'reptile', 'fr': 'Python réticulé', 'sci': 'Malayopython reticulatus'},
    {'class': 'reptile', 'fr': 'Python vert', 'sci': 'Morelia viridis'},
    {'class': 'reptile', 'fr': 'Python tapis', 'sci': 'Morelia spilota'},
    {'class': 'reptile', 'fr': 'Python de Seba', 'sci': 'Python sebae'},
    {'class': 'reptile', 'fr': 'Python molure', 'sci': 'Python bivittatus'},
    {'class': 'reptile', 'fr': 'Boa constricteur', 'sci': 'Boa constrictor'},
    {'class': 'reptile', 'fr': 'Boa arc-en-ciel', 'sci': 'Epicrates cenchria'},
    {'class': 'reptile', 'fr': 'Boa émeraude', 'sci': 'Corallus caninus'},
    {'class': 'reptile', 'fr': "Boa de l'île Ronde", 'sci': 'Casarea dussumieri'},
    {'class': 'reptile', 'fr': 'Couleuvre des blés', 'sci': 'Pantherophis guttatus'},
    {'class': 'reptile', 'fr': 'Couleuvre royale', 'sci': 'Lampropeltis getula'},
    {'class': 'reptile', 'fr': 'Couleuvre faux-corail', 'sci': 'Lampropeltis triangulum'},
    {'class': 'reptile', 'fr': 'Couleuvre ratière', 'sci': 'Elaphe obsoleta'},
    {'class': 'reptile', 'fr': 'Couleuvre à nez plat', 'sci': 'Heterodon nasicus'},
    {'class': 'reptile', 'fr': 'Couleuvre verte', 'sci': 'Opheodrys aestivus'},
    {'class': 'reptile', 'fr': 'Serpent des blés', 'sci': 'Pantherophis emoryi'},
    {'class': 'reptile', 'fr': 'Serpent roi de Californie', 'sci': 'Lampropeltis californiae'},
    {'class': 'reptile', 'fr': 'Serpent des sables', 'sci': 'Eryx johnii'},
    {'class': 'reptile', 'fr': 'Serpent de lait hondurien', 'sci': 'Lampropeltis triangulum hondurensis'},
    {'class': 'reptile', 'fr': 'Tortue grecque', 'sci': 'Testudo graeca'},
    {'class': 'reptile', 'fr': "Tortue d'Hermann", 'sci': 'Testudo hermanni'},
    {'class': 'reptile', 'fr': 'Tortue bordée', 'sci': 'Testudo marginata'},
    {'class': 'reptile', 'fr': 'Tortue sulcata', 'sci': 'Centrochelys sulcata'},
    {'class': 'reptile', 'fr': 'Tortue étoilée', 'sci': 'Geochelone elegans'},
    {'class': 'reptile', 'fr': 'Tortue radiée', 'sci': 'Astrochelys radiata'},
    {'class': 'reptile', 'fr': 'Tortue léopard', 'sci': 'Stigmochelys pardalis'},
    {'class': 'reptile', 'fr': 'Tortue géante des Galapagos', 'sci': 'Chelonoidis nigra'},
    {'class': 'reptile', 'fr': 'Tortue de Floride', 'sci': 'Trachemys scripta elegans'},
    {'class': 'reptile', 'fr': 'Tortue palustre', 'sci': 'Emys orbicularis'},
    {'class': 'reptile', 'fr': 'Tortue musquée', 'sci': 'Sternotherus odoratus'},
    {'class': 'reptile', 'fr': 'Tortue map', 'sci': 'Graptemys geographica'},
    {'class': 'reptile', 'fr': 'Tortue à cou serpent', 'sci': 'Chelodina longicollis'},
    {'class': 'reptile', 'fr': 'Tortue à oreilles rouges', 'sci': 'Trachemys scripta'},
    {'class': 'reptile', 'fr': 'Crocodile nain', 'sci': 'Osteolaemus tetraspis'},
    {'class': 'reptile', 'fr': 'Caïman à lunettes', 'sci': 'Caiman crocodilus'},
    {'class': 'reptile', 'fr': "Alligator d'Amérique", 'sci': 'Alligator mississippiensis'},
    {'class': 'reptile', 'fr': 'Gecko tokay', 'sci': 'Gekko gecko'},
    {'class': 'reptile', 'fr': 'Lézard des murailles', 'sci': 'Podarcis muralis'},
    {'class': 'reptile', 'fr': 'Scinque à cou rouge', 'sci': 'Cryptoblepharus virgatus'},
    {'class': 'reptile', 'fr': "Serpent des blés de l'Ouest", 'sci': 'Pantherophis obsoletus'},
    {'class': 'reptile', 'fr': 'Boiga brune', 'sci': 'Boiga irregularis'},
    {'class': 'reptile', 'fr': 'Couleuvre de Vigneau', 'sci': 'Coronella girondica'},
    {'class': 'amphibian', 'fr': 'Grenouille cornue', 'sci': 'Ceratophrys ornata'},
    {'class': 'amphibian', 'fr': 'Grenouille cornue de Cranwell', 'sci': 'Ceratophrys cranwelli'},
    {'class': 'amphibian', 'fr': 'Grenouille tomate', 'sci': 'Dyscophus antongilii'},
    {'class': 'amphibian', 'fr': 'Grenouille verte', 'sci': 'Pelophylax kl. esculentus'},
    {'class': 'amphibian', 'fr': 'Rainette aux yeux rouges', 'sci': 'Agalychnis callidryas'},
    {'class': 'amphibian', 'fr': 'Rainette de White', 'sci': 'Litoria caerulea'},
    {'class': 'amphibian', 'fr': "Rainette verte d'Amérique", 'sci': 'Hyla cinerea'},
    {'class': 'amphibian', 'fr': 'Rainette à doigts de cuivre', 'sci': 'Hyla arborea'},
    {'class': 'amphibian', 'fr': 'Dendrobate à tapirer', 'sci': 'Dendrobates tinctorius'},
    {'class': 'amphibian', 'fr': 'Dendrobate lépreux', 'sci': 'Dendrobates leucomelas'},
    {'class': 'amphibian', 'fr': 'Dendrobate à ventre tacheté', 'sci': 'Dendrobates auratus'},
    {'class': 'amphibian', 'fr': 'Dendrobate bleu', 'sci': 'Dendrobates azureus'},
    {'class': 'amphibian', 'fr': 'Grenouille de Dart', 'sci': 'Oophaga pumilio'},
    {'class': 'amphibian', 'fr': 'Grenouille arboricole géante', 'sci': 'Rhacophorus maximus'},
    {'class': 'amphibian', 'fr': 'Grenouille du lac Titicaca', 'sci': 'Telmatobius culeus'},
    {'class': 'amphibian', 'fr': 'Crapaud buffle', 'sci': 'Rhinella marina'},
    {'class': 'amphibian', 'fr': 'Crapaud commun', 'sci': 'Bufo bufo'},
    {'class': 'amphibian', 'fr': 'Crapaud à ventre de feu', 'sci': 'Bombina orientalis'},
    {'class': 'amphibian', 'fr': 'Crapaud de Fowler', 'sci': 'Anaxyrus fowleri'},
    {'class': 'amphibian', 'fr': 'Salamandre tachetée', 'sci': 'Salamandra salamandra'},
    {'class': 'amphibian', 'fr': 'Salamandre géante du Japon', 'sci': 'Andrias japonicus'},
    {'class': 'amphibian', 'fr': 'Salamandre de Taiwan', 'sci': 'Hynobius formosanus'},
    {'class': 'amphibian', 'fr': 'Triton crêté', 'sci': 'Triturus cristatus'},
    {'class': 'amphibian', 'fr': 'Triton alpestre', 'sci': 'Ichthyosaura alpestris'},
    {'class': 'amphibian', 'fr': 'Triton marbré', 'sci': 'Triturus marmoratus'},
    {'class': 'amphibian', 'fr': 'Axolotl', 'sci': 'Ambystoma mexicanum'},
    {'class': 'amphibian', 'fr': 'Xénope lisse', 'sci': 'Xenopus laevis'},
    {'class': 'amphibian', 'fr': 'Grenouille de Verre', 'sci': 'Hyalinobatrachium valerioi'},
    {'class': 'amphibian', 'fr': "Grenouille venimeuse de l'Amazone", 'sci': 'Ameerega trivittata'},
    {'class': 'fish', 'fr': 'Guppy', 'sci': 'Poecilia reticulata'},
    {'class': 'fish', 'fr': 'Néon bleu', 'sci': 'Paracheirodon innesi'},
    {'class': 'fish', 'fr': 'Néon cardinalis', 'sci': 'Paracheirodon axelrodi'},
    {'class': 'fish', 'fr': 'Néon noir', 'sci': 'Hyphessobrycon herbertaxelrodi'},
    {'class': 'fish', 'fr': 'Tétra citron', 'sci': 'Hyphessobrycon pulchripinnis'},
    {'class': 'fish', 'fr': 'Tétra empereur', 'sci': 'Nematobrycon palmeri'},
    {'class': 'fish', 'fr': 'Tétra du Congo', 'sci': 'Phenacogrammus interruptus'},
    {'class': 'fish', 'fr': 'Tétra fantôme noir', 'sci': 'Hyphessobrycon megalopterus'},
    {'class': 'fish', 'fr': 'Discus', 'sci': 'Symphysodon discus'},
    {'class': 'fish', 'fr': 'Scalaire', 'sci': 'Pterophyllum scalare'},
    {'class': 'fish', 'fr': 'Betta splendens', 'sci': 'Betta splendens'},
    {'class': 'fish', 'fr': 'Oscar', 'sci': 'Astronotus ocellatus'},
    {'class': 'fish', 'fr': 'Cichlidé convict', 'sci': 'Amatitlania nigrofasciata'},
    {'class': 'fish', 'fr': 'Cichlidé de Jack Dempsey', 'sci': 'Rocio octofasciata'},
    {'class': 'fish', 'fr': 'Cichlidé de Ramirezi', 'sci': 'Mikrogeophagus ramirezi'},
    {'class': 'fish', 'fr': 'Cichlidé perroquet', 'sci': 'Amphilophus citrinellus'},
    {'class': 'fish', 'fr': 'Cichlidé frontosa', 'sci': 'Cyphotilapia frontosa'},
    {'class': 'fish', 'fr': 'Cichlidé zèbre', 'sci': 'Metriaclima zebra'},
    {'class': 'fish', 'fr': 'Cichlidé jaune', 'sci': 'Labidochromis caeruleus'},
    {'class': 'fish', 'fr': 'Barbu cerise', 'sci': 'Puntius titteya'},
    {'class': 'fish', 'fr': 'Barbu de Sumatra', 'sci': 'Puntigrus tetrazona'},
    {'class': 'fish', 'fr': 'Barbu rosé', 'sci': 'Pethia conchonius'},
    {'class': 'fish', 'fr': 'Danio zébré', 'sci': 'Danio rerio'},
    {'class': 'fish', 'fr': 'Danio géant', 'sci': 'Devario aequipinnatus'},
    {'class': 'fish', 'fr': 'Molly voile', 'sci': 'Poecilia latipinna'},
    {'class': 'fish', 'fr': 'Platy', 'sci': 'Xiphophorus maculatus'},
    {'class': 'fish', 'fr': 'Xipho', 'sci': 'Xiphophorus hellerii'},
    {'class': 'fish', 'fr': 'Corydoras panda', 'sci': 'Corydoras panda'},
    {'class': 'fish', 'fr': 'Corydoras bronze', 'sci': 'Corydoras aeneus'},
    {'class': 'fish', 'fr': 'Corydoras sterbai', 'sci': 'Corydoras sterbai'},
    {'class': 'fish', 'fr': 'Otocinclus', 'sci': 'Otocinclus affinis'},
    {'class': 'fish', 'fr': 'Pleco commun', 'sci': 'Hypostomus plecostomus'},
    {'class': 'fish', 'fr': 'Pleco royal', 'sci': 'Panaque nigrolineatus'},
    {'class': 'fish', 'fr': 'Ancistrus', 'sci': 'Ancistrus cirrhosus'},
    {'class': 'fish', 'fr': 'Poisson-papillon', 'sci': 'Pantodon buchholzi'},
    {'class': 'fish', 'fr': 'Poisson-archer', 'sci': 'Toxotes jaculatrix'},
    {'class': 'fish', 'fr': 'Poisson éléphant', 'sci': 'Gnathonemus petersii'},
    {'class': 'fish', 'fr': 'Poisson-chat de verre', 'sci': 'Kryptopterus vitreolus'},
    {'class': 'fish', 'fr': 'Koi', 'sci': 'Cyprinus rubrofuscus'},
    {'class': 'fish', 'fr': 'Poisson rouge', 'sci': 'Carassius auratus'},
    {'class': 'fish', 'fr': 'Gourami nain', 'sci': 'Trichogaster lalius'},
    {'class': 'fish', 'fr': 'Gourami perlé', 'sci': 'Trichopodus leeri'},
    {'class': 'fish', 'fr': 'Gourami bleu', 'sci': 'Trichogaster trichopterus'},
    {'class': 'fish', 'fr': 'Apistogramma cacatuoides', 'sci': 'Apistogramma cacatuoides'},
    {'class': 'fish', 'fr': 'Killie', 'sci': 'Aphyosemion australe'},
    {'class': 'fish', 'fr': 'Tétras de Buenos Aires', 'sci': 'Hyphessobrycon anisitsi'},
    {'class': 'invertebrate', 'fr': 'Tarentule de Gordon', 'sci': 'Grammostola rosea'},
    {'class': 'invertebrate', 'fr': 'Tarentule mexicaine à genoux rouges', 'sci': 'Brachypelma smithi'},
    {'class': 'invertebrate', 'fr': 'Tarentule mexicaine à genoux oranges', 'sci': 'Brachypelma auratum'},
    {'class': 'invertebrate', 'fr': 'Tarentule à pattes roses', 'sci': 'Avicularia avicularia'},
    {'class': 'invertebrate', 'fr': 'Tarentule Goliath', 'sci': 'Theraphosa blondi'},
    {'class': 'invertebrate', 'fr': 'Tarentule saumonée', 'sci': 'Lasiodora parahybana'},
    {'class': 'invertebrate', 'fr': 'Tarentule de Cobalt', 'sci': 'Cyriopagopus lividus'},
    {'class': 'invertebrate', 'fr': 'Scorpion empereur', 'sci': 'Pandinus imperator'},
    {'class': 'invertebrate', 'fr': 'Scorpion à queue jaune', 'sci': 'Androctonus australis'},
    {'class': 'invertebrate', 'fr': 'Scorpion des Pyrénées', 'sci': 'Buthus occitanus'},
    {'class': 'invertebrate', 'fr': 'Scorpion à griffes fines', 'sci': 'Euscorpius italicus'},
    {'class': 'invertebrate', 'fr': 'Phasme bâton', 'sci': 'Carausius morosus'},
    {'class': 'invertebrate', 'fr': 'Phasme feuille', 'sci': 'Phyllium philippinicum'},
    {'class': 'invertebrate', 'fr': 'Mante religieuse', 'sci': 'Mantis religiosa'},
    {'class': 'invertebrate', 'fr': 'Mante orchidée', 'sci': 'Hymenopus coronatus'},
    {'class': 'invertebrate', 'fr': 'Blatte de Madagascar', 'sci': 'Gromphadorhina portentosa'},
    {'class': 'invertebrate', 'fr': 'Escargot géant africain', 'sci': 'Achatina fulica'},
    {'class': 'invertebrate', 'fr': 'Escargot de Bourgogne', 'sci': 'Helix pomatia'},
    {'class': 'invertebrate', 'fr': 'Crevette Red Cherry', 'sci': 'Neocaridina davidi'},
    {'class': 'invertebrate', 'fr': 'Crevette Amano', 'sci': 'Caridina multidentata'},
    {'class': 'invertebrate', 'fr': "Bernard-l'ermite terrestre", 'sci': 'Coenobita clypeatus'},
    {'class': 'invertebrate', 'fr': 'Cloporte géant', 'sci': 'Porcellio laevis'},
    {'class': 'invertebrate', 'fr': 'Mille-pattes géant', 'sci': 'Archispirostreptus gigas'},
]
