-- Même nettoyage que 20261003200000_breeds_template_sections_cleanup, pour les fiches ESPÈCES
-- (< 2 000 000 001) qui ont reçu une section du modèle générique de breeds-data.json en
-- production (ex. Python réticulé ou Tortue grecque « insectivore, guide gecko »).
-- Ne supprime que les lignes de section dont une source porte l'empreinte d'un modèle
-- (titres de prisma/templates/*.json) : aucune fiche curée ne cite ces titres (0 ligne sur une
-- base neuve migrée et seedée). Idempotente. Le seed (skipDuplicates) peut ensuite réinsérer
-- les sections curées. Législation exclue : pas d'empreinte fiable.
DELETE FROM "SpeciesFeeding" AS s
WHERE s."speciesId" < 2000000001
  AND jsonb_typeof(s."sources") = 'array'
  AND EXISTS (
    SELECT 1 FROM jsonb_array_elements(s."sources") AS src
    WHERE src->>'title' = ANY (ARRAY[
    'PetMD — santé canine',
    'PetMD — santé féline',
    'Royal Canin — guide alimentation chat',
    'Royal Canin — guide alimentation chien',
    'Royal Canin — guide alimentation lapin',
    'Royal Canin — nutrition équine',
    'VCA Hospitals — lapin',
    'VCA Hospitals — lapin santé',
    'VCA Hospitals — maladies du chat',
    'VCA Hospitals — maladies du chien',
    'VCA Hospitals — santé chat',
    'VCA Hospitals — santé chien',
    'VCA Hospitals — santé des arachnides',
    'VCA Hospitals — santé des oiseaux',
    'VCA Hospitals — santé des poissons',
    'VCA Hospitals — santé des reptiles',
    'VCA Hospitals — santé des volailles',
    'VCA Hospitals — santé équine',
    'VCA Hospitals — soins des arachnides',
    'VCA Hospitals — soins des oiseaux',
    'VCA Hospitals — soins des poissons',
    'VCA Hospitals — soins des reptiles',
    'VCA Hospitals — soins des rongeurs',
    'VCA Hospitals — soins des volailles',
    'VCA Hospitals — soins du chat',
    'VCA Hospitals — soins du chien',
    'Wamiz — guide aquarium',
    'Wamiz — guide chat',
    'Wamiz — guide cheval',
    'Wamiz — guide chien',
    'Wamiz — guide gecko',
    'Wamiz — guide lapin',
    'Wamiz — guide mygale',
    'Wamiz — guide perruche',
    'Wamiz — guide poule',
    'Wamiz — santé aquarium',
    'Wamiz — santé de la perruche',
    'Wamiz — santé de la poule',
    'Wamiz — santé du cheval',
    'Wamiz — santé du gecko',
    'Wamiz — santé du lapin',
    'Wamiz — santé mygale',
    'Wikipédia — page de référence (chat)',
    'Wikipédia — page de référence (cheval)',
    'Wikipédia — page de référence (chien)',
    'Wikipédia — page de référence (gecko)',
    'Wikipédia — page de référence (lapin)',
    'Wikipédia — page de référence (mygale)',
    'Wikipédia — page de référence (perruche)',
    'Wikipédia — page de référence (poisson)',
    'Wikipédia — page de référence (poule)'
  ]::text[])
  );

DELETE FROM "SpeciesHabitat" AS s
WHERE s."speciesId" < 2000000001
  AND jsonb_typeof(s."sources") = 'array'
  AND EXISTS (
    SELECT 1 FROM jsonb_array_elements(s."sources") AS src
    WHERE src->>'title' = ANY (ARRAY[
    'PetMD — santé canine',
    'PetMD — santé féline',
    'Royal Canin — guide alimentation chat',
    'Royal Canin — guide alimentation chien',
    'Royal Canin — guide alimentation lapin',
    'Royal Canin — nutrition équine',
    'VCA Hospitals — lapin',
    'VCA Hospitals — lapin santé',
    'VCA Hospitals — maladies du chat',
    'VCA Hospitals — maladies du chien',
    'VCA Hospitals — santé chat',
    'VCA Hospitals — santé chien',
    'VCA Hospitals — santé des arachnides',
    'VCA Hospitals — santé des oiseaux',
    'VCA Hospitals — santé des poissons',
    'VCA Hospitals — santé des reptiles',
    'VCA Hospitals — santé des volailles',
    'VCA Hospitals — santé équine',
    'VCA Hospitals — soins des arachnides',
    'VCA Hospitals — soins des oiseaux',
    'VCA Hospitals — soins des poissons',
    'VCA Hospitals — soins des reptiles',
    'VCA Hospitals — soins des rongeurs',
    'VCA Hospitals — soins des volailles',
    'VCA Hospitals — soins du chat',
    'VCA Hospitals — soins du chien',
    'Wamiz — guide aquarium',
    'Wamiz — guide chat',
    'Wamiz — guide cheval',
    'Wamiz — guide chien',
    'Wamiz — guide gecko',
    'Wamiz — guide lapin',
    'Wamiz — guide mygale',
    'Wamiz — guide perruche',
    'Wamiz — guide poule',
    'Wamiz — santé aquarium',
    'Wamiz — santé de la perruche',
    'Wamiz — santé de la poule',
    'Wamiz — santé du cheval',
    'Wamiz — santé du gecko',
    'Wamiz — santé du lapin',
    'Wamiz — santé mygale',
    'Wikipédia — page de référence (chat)',
    'Wikipédia — page de référence (cheval)',
    'Wikipédia — page de référence (chien)',
    'Wikipédia — page de référence (gecko)',
    'Wikipédia — page de référence (lapin)',
    'Wikipédia — page de référence (mygale)',
    'Wikipédia — page de référence (perruche)',
    'Wikipédia — page de référence (poisson)',
    'Wikipédia — page de référence (poule)'
  ]::text[])
  );

DELETE FROM "SpeciesBehavior" AS s
WHERE s."speciesId" < 2000000001
  AND jsonb_typeof(s."sources") = 'array'
  AND EXISTS (
    SELECT 1 FROM jsonb_array_elements(s."sources") AS src
    WHERE src->>'title' = ANY (ARRAY[
    'PetMD — santé canine',
    'PetMD — santé féline',
    'Royal Canin — guide alimentation chat',
    'Royal Canin — guide alimentation chien',
    'Royal Canin — guide alimentation lapin',
    'Royal Canin — nutrition équine',
    'VCA Hospitals — lapin',
    'VCA Hospitals — lapin santé',
    'VCA Hospitals — maladies du chat',
    'VCA Hospitals — maladies du chien',
    'VCA Hospitals — santé chat',
    'VCA Hospitals — santé chien',
    'VCA Hospitals — santé des arachnides',
    'VCA Hospitals — santé des oiseaux',
    'VCA Hospitals — santé des poissons',
    'VCA Hospitals — santé des reptiles',
    'VCA Hospitals — santé des volailles',
    'VCA Hospitals — santé équine',
    'VCA Hospitals — soins des arachnides',
    'VCA Hospitals — soins des oiseaux',
    'VCA Hospitals — soins des poissons',
    'VCA Hospitals — soins des reptiles',
    'VCA Hospitals — soins des rongeurs',
    'VCA Hospitals — soins des volailles',
    'VCA Hospitals — soins du chat',
    'VCA Hospitals — soins du chien',
    'Wamiz — guide aquarium',
    'Wamiz — guide chat',
    'Wamiz — guide cheval',
    'Wamiz — guide chien',
    'Wamiz — guide gecko',
    'Wamiz — guide lapin',
    'Wamiz — guide mygale',
    'Wamiz — guide perruche',
    'Wamiz — guide poule',
    'Wamiz — santé aquarium',
    'Wamiz — santé de la perruche',
    'Wamiz — santé de la poule',
    'Wamiz — santé du cheval',
    'Wamiz — santé du gecko',
    'Wamiz — santé du lapin',
    'Wamiz — santé mygale',
    'Wikipédia — page de référence (chat)',
    'Wikipédia — page de référence (cheval)',
    'Wikipédia — page de référence (chien)',
    'Wikipédia — page de référence (gecko)',
    'Wikipédia — page de référence (lapin)',
    'Wikipédia — page de référence (mygale)',
    'Wikipédia — page de référence (perruche)',
    'Wikipédia — page de référence (poisson)',
    'Wikipédia — page de référence (poule)'
  ]::text[])
  );

DELETE FROM "SpeciesHealthContent" AS s
WHERE s."speciesId" < 2000000001
  AND jsonb_typeof(s."sources") = 'array'
  AND EXISTS (
    SELECT 1 FROM jsonb_array_elements(s."sources") AS src
    WHERE src->>'title' = ANY (ARRAY[
    'PetMD — santé canine',
    'PetMD — santé féline',
    'Royal Canin — guide alimentation chat',
    'Royal Canin — guide alimentation chien',
    'Royal Canin — guide alimentation lapin',
    'Royal Canin — nutrition équine',
    'VCA Hospitals — lapin',
    'VCA Hospitals — lapin santé',
    'VCA Hospitals — maladies du chat',
    'VCA Hospitals — maladies du chien',
    'VCA Hospitals — santé chat',
    'VCA Hospitals — santé chien',
    'VCA Hospitals — santé des arachnides',
    'VCA Hospitals — santé des oiseaux',
    'VCA Hospitals — santé des poissons',
    'VCA Hospitals — santé des reptiles',
    'VCA Hospitals — santé des volailles',
    'VCA Hospitals — santé équine',
    'VCA Hospitals — soins des arachnides',
    'VCA Hospitals — soins des oiseaux',
    'VCA Hospitals — soins des poissons',
    'VCA Hospitals — soins des reptiles',
    'VCA Hospitals — soins des rongeurs',
    'VCA Hospitals — soins des volailles',
    'VCA Hospitals — soins du chat',
    'VCA Hospitals — soins du chien',
    'Wamiz — guide aquarium',
    'Wamiz — guide chat',
    'Wamiz — guide cheval',
    'Wamiz — guide chien',
    'Wamiz — guide gecko',
    'Wamiz — guide lapin',
    'Wamiz — guide mygale',
    'Wamiz — guide perruche',
    'Wamiz — guide poule',
    'Wamiz — santé aquarium',
    'Wamiz — santé de la perruche',
    'Wamiz — santé de la poule',
    'Wamiz — santé du cheval',
    'Wamiz — santé du gecko',
    'Wamiz — santé du lapin',
    'Wamiz — santé mygale',
    'Wikipédia — page de référence (chat)',
    'Wikipédia — page de référence (cheval)',
    'Wikipédia — page de référence (chien)',
    'Wikipédia — page de référence (gecko)',
    'Wikipédia — page de référence (lapin)',
    'Wikipédia — page de référence (mygale)',
    'Wikipédia — page de référence (perruche)',
    'Wikipédia — page de référence (poisson)',
    'Wikipédia — page de référence (poule)'
  ]::text[])
  );

DELETE FROM "SpeciesReproduction" AS s
WHERE s."speciesId" < 2000000001
  AND jsonb_typeof(s."sources") = 'array'
  AND EXISTS (
    SELECT 1 FROM jsonb_array_elements(s."sources") AS src
    WHERE src->>'title' = ANY (ARRAY[
    'PetMD — santé canine',
    'PetMD — santé féline',
    'Royal Canin — guide alimentation chat',
    'Royal Canin — guide alimentation chien',
    'Royal Canin — guide alimentation lapin',
    'Royal Canin — nutrition équine',
    'VCA Hospitals — lapin',
    'VCA Hospitals — lapin santé',
    'VCA Hospitals — maladies du chat',
    'VCA Hospitals — maladies du chien',
    'VCA Hospitals — santé chat',
    'VCA Hospitals — santé chien',
    'VCA Hospitals — santé des arachnides',
    'VCA Hospitals — santé des oiseaux',
    'VCA Hospitals — santé des poissons',
    'VCA Hospitals — santé des reptiles',
    'VCA Hospitals — santé des volailles',
    'VCA Hospitals — santé équine',
    'VCA Hospitals — soins des arachnides',
    'VCA Hospitals — soins des oiseaux',
    'VCA Hospitals — soins des poissons',
    'VCA Hospitals — soins des reptiles',
    'VCA Hospitals — soins des rongeurs',
    'VCA Hospitals — soins des volailles',
    'VCA Hospitals — soins du chat',
    'VCA Hospitals — soins du chien',
    'Wamiz — guide aquarium',
    'Wamiz — guide chat',
    'Wamiz — guide cheval',
    'Wamiz — guide chien',
    'Wamiz — guide gecko',
    'Wamiz — guide lapin',
    'Wamiz — guide mygale',
    'Wamiz — guide perruche',
    'Wamiz — guide poule',
    'Wamiz — santé aquarium',
    'Wamiz — santé de la perruche',
    'Wamiz — santé de la poule',
    'Wamiz — santé du cheval',
    'Wamiz — santé du gecko',
    'Wamiz — santé du lapin',
    'Wamiz — santé mygale',
    'Wikipédia — page de référence (chat)',
    'Wikipédia — page de référence (cheval)',
    'Wikipédia — page de référence (chien)',
    'Wikipédia — page de référence (gecko)',
    'Wikipédia — page de référence (lapin)',
    'Wikipédia — page de référence (mygale)',
    'Wikipédia — page de référence (perruche)',
    'Wikipédia — page de référence (poisson)',
    'Wikipédia — page de référence (poule)'
  ]::text[])
  );

